# Generated by Django 5.1.1 on 2025-04-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('SF1', 'Sefmi-final 1'), ('SF2', 'Semi-final 2'), ('GF', 'Grand final')], default='spring', max_length=50)),
            ],
            options={
                'verbose_name': 'Global state',
                'verbose_name_plural': 'Global state',
            },
        ),
    ]
