# Generated by Django 5.1.1 on 2025-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='state',
            field=models.CharField(choices=[('SF1', 'Sefmi-final 1'), ('SF2', 'Semi-final 2'), ('GF', 'Grand final')], default='SF1', max_length=50),
        ),
    ]
