# Generated by Django 5.1.1 on 2025-05-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_globalsettings_state'),
        ('tools', '0002_alter_performance_jury_alter_performance_passed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='id',
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='state',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='global_settings', serialize=False, to='tools.show'),
        ),
    ]
