# Generated by Django 5.1.1 on 2025-05-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_globalsettings_id_alter_globalsettings_state'),
        ('tools', '0003_alter_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='state',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='global_settings', to='tools.show'),
        ),
    ]
