# Generated by Django 5.1.1 on 2025-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_account_username_account_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pass_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
