# Generated by Django 5.1.1 on 2025-04-27 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0002_alter_performance_jury_alter_performance_passed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.performance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'rank'), name='unique_user_rank'), models.UniqueConstraint(fields=('user', 'performance'), name='unique_user_participant')],
            },
        ),
    ]
