# Generated by Django 5.1.1 on 2025-04-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SF1', 'Semi-Final 1'), ('SF2', 'Semi-Final 2'), ('GF', 'Grand Final')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('points', models.IntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('jury', models.IntegerField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.participant')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.show')),
            ],
            options={
                'unique_together': {('participant', 'show')},
            },
        ),
    ]
