# Generated by Django 5.1.1 on 2025-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_performance_jury_alter_performance_passed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(choices=[('SF1', 'Semi Final 1'), ('SF2', 'Semi Final 2'), ('GF', 'Grand Final')], max_length=3, unique=True),
        ),
    ]
