# Generated by Django 5.1.1 on 2025-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='criteria',
            field=models.IntegerField(choices=[(1, 'Qualified'), (2, 'Musical Quality'), (3, 'Stage Performance'), (4, 'Visual Presentation')], default=1),
            preserve_default=False,
        ),
    ]
