# Generated by Django 5.1.1 on 2025-05-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_vote_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(choices=[('SF1', 'Semi Final 1'), ('SF2', 'Semi Final 2'), ('GF', 'Grand Final'), ('N', 'End')], max_length=3, unique=True),
        ),
    ]
